#spring.application.name=Timesheets
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
